name: MeetUp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #for integrating firebase
  firebase_core: ^2.15.0

  #for handling fire base authentication
  firebase_auth: ^4.7.2

  #handling google sign in
  google_sign_in: ^6.1.4

  #for accesing cloud firestore database:
  cloud_firestore: ^4.8.4

  #For showing network images
  cached_network_image: ^3.2.3

  #profile picture
  image_picker: ^1.0.2

  #For accessing firebase storage(uploading image)
  firebase_storage: ^11.2.5

  #for emogi
  emoji_picker_flutter: ^1.6.1

  #for saving immages
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

#
#  flutter_launcher_icons: "^0.13.1"
#
#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "images/laugh.png"
#  min_sdk_android: 21
#  remove_alpha_ios: true

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg



  fonts:
    - family: Caveat
      fonts:
        - asset: fonts/Caveat-VariableFont_wght.ttf
#        - asset: fonts/Caveat-Italic.ttf
#          style: italic
#        - asset: fonts/Caveat-Bold.ttf
#          weight: 700